  
language: cpp
sudo: required

os:
  - linux

compiler:
  - gcc

env:
  CODECOV_TOKEN='6ea2abaa-7592-425e-9cd3-6375a7834cc8'

before_install:
  - sudo apt-get -y install libgtest-dev

install:
  - wget --quiet -O - https://raw.githubusercontent.com/r-lyeh/depot/master/travis.pre.sh | bash -x

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - pwd
  - make